### ISSUE TITLE
How to use DLGWAS?

### ISSUE THREAD

**Issue by WHSmyself** [DanielKick-USDA/dlgwas#1]
I have installed this software on Ubuntu following the steps, but the installed files are different from the ones you provided. I would like to know how to use this software.

**Comment by DanielKick-USDA** [comment]
Hi there @WHSmyself. I would not recommend using this project at present. Rather, there is a nearly feature complete version that is considerably faster which will publicly available soon (with install and use instructions). If you're interested in being involved in the early testing, please let me know.

**Comment by WHSmyself** [comment]
Thank you for your reply! I hope to participate in your project. If you could provide a complete version, I would greatly appreciate it!

**Comment by DanielKick-USDA** [comment]
Sounds good.  Please email me at Daniel.Kick@usda.gov with some details on your use case. Worst case scenario, if for some reason I am not able to share this, the public version should be available here within the next few months.

**Comment by DanielKick-USDA** [comment]
Sounds good. Please email me at [Daniel.Kick@usda.gov](mailto:Daniel.Kick@usda.gov) with some details on your use case. Worst case scenario, if for some reason I am not able to share this, the public version should be available here within the next few months.
